.\" Manpage for Carch
.TH "carch" "1" "March 2025" "Carch 4.1.6" "Carch Manual"

.SH NAME
carch \- Automate Your Linux Setup

.SH SYNOPSIS
\fBcarch [OPTIONS]\fR

.SH DESCRIPTION
Carch is a versatile tool designed to automate and streamline the process of setting up Arch Linux and Fedora systems. 
.br
It provides support for both CLI interfaces, configuration management, and logging. 
.br
With Carch, you can efficiently customize your Arch Linux installation to meet your specific needs.

.SH LIVE VERSION
Get started quickly with the live version by running the following command in your terminal:
.PP
\fBcurl -fsSL https://chalisehari.com.np/carchx | sh\fR

.SH OPTIONS
.TP
\fB\-\-help\fR, \fB\-h\fR
Display this help message and exit.

.TP
\fB\-\-version\fR, \fB\-v\fR
Show the current version of the program (\fB4.1.6\fR).

.TP
\fB\-\-gen\-config\fR
Generate a default configuration file in ~/.config/carch/carch.conf.

.TP
\fB\-\-config\fR \fI<conf dir>\fR
Use a specific configuration file to load selected scripts.

.TP
\fB\-c\fR
Use the default configuration file to load selected scripts.

.TP
\fB\-\-run\-script\fR \fI<name>\fR
Execute the specified script from the script directory (\fB$SCRIPT_DIR\fR).

.TP
\fB\-\-list\-scripts\fR, \fB\-l\fR
List all available scripts in the script directory (\fB$SCRIPT_DIR\fR).

.TP
\fB\-\-update\fR
Update Carch by downloading and applying the latest script version.

.TP
\fB\-\-uninstall\fR
Uninstall Carch and remove all associated files.

.SH SUPPORT
For assistance or to report issues, visit the official repository:
.br
https://github.com/harilvfs/carch

.SH DOCUMENTATION
Comprehensive documentation for Carch is available at:
.br
https://carch-org.github.io/docs/

.SH AUTHOR
Carch was developed and is maintained by Hari Chalise.
.br
Contact: \fIhari@chalisehari.com.np\fR

.SH REPORTING BUGS
If you encounter bugs or issues, please report them at:
.br
https://github.com/harilvfs/carch/issues

.SH COPYRIGHT
Copyright (c) 2025 Hari Chalise.
.br
Released under the GPL-3.0 License.
.br
Full license details: https://www.gnu.org/licenses/gpl-3.0.en.html

