.\" Manpage for Carch
.TH "carch" "1" "July 2025" "Carch 5.2.1" "Carch Manual"

.SH NAME
carch \- Automate Your Linux Setup

.SH SYNOPSIS
\fBcarch [OPTIONS]\fR

.SH DESCRIPTION
A simple CLI tool to automate Linux system setup 🧩
.br
It offers automated scripts that save users time setting up their Linux environment.

.SH USAGE
You can run or use Carch directly without installing it on your system.

Choose one of the following versions to try Carch:

.PP
⭐ Stable Version [ Latest Release ]
.br
To get the stable version, run:
.nf
bash -c "$(curl -fsSL chalisehari.com.np/carch)"
.fi

.PP
🧪 Dev Version [ Pre-Release ]
.br
To get the development version, run:
.nf
bash -c "$(curl -fsSL chalisehari.com.np/carchdev)"
.fi

.SH OPTIONS
.TP
\fB\-\-help\fR, \fB\-h\fR
Display this help message and exit.

.TP
\fB\-\-version\fR, \fB\-v\fR
Show the current version of the program.

.TP
\fB\-\-list\-scripts\fR, \fB\-l\fR
List all available scripts.

.TP
\fB\-\-no\-preview\fR
Run without displaying script previews in menus.

.TP
\fB\-\-log\fR
Enable logging for the current session only.

.TP
\fB\-\-update\fR
Get instructions for updating Carch.

.TP
\fB\-\-check\-update\fR
Check if a new version of Carch is available.

.TP
\fB\-\-uninstall\fR
Get instructions for uninstalling Carch.

.SH SUPPORT
For assistance or to report issues, visit the official repository:
.br
https://github.com/harilvfs/carch

.SH DOCUMENTATION
Comprehensive documentation for Carch is available at:
.br
https://carch.chalisehari.com.np

.SH AUTHOR
Carch was developed and is maintained by Hari Chalise.
.br
Contact: \fIharilvfs@chalisehari.com.np\fR

.SH REPORTING BUGS
If you encounter bugs or issues, please report them at:
.br
https://github.com/harilvfs/carch/issues

.SH COPYRIGHT
Copyright (c) 2025 Hari Chalise.
.br
Released under the MIT License.
.br
Full license details: https://opensource.org/license/mit
