.\" Manpage for Carch
.TH "carch" "1" "July 2025" "Carch 5.2.6" "Carch Manual"

.SH NAME
carch \- Automate Your Linux System Setup

.SH SYNOPSIS
\fBcarch [OPTIONS]\fR

.SH DESCRIPTION
A simple CLI tool to automate Linux system setup 🧩
.br
It offers automated scripts that save users time setting up their Linux environment.

.SH USAGE
You can run or use Carch directly without installing it on your system.

Choose one of the following versions to try Carch:

.PP
⭐ Stable Version [ Latest Release ]
.br
To get the stable version, run:
.nf
bash -c "$(curl -fsSL chalisehari.com.np/carch)"
.fi

.PP
🧪 Dev Version [ Pre-Release ]
.br
To get the development version, run:
.nf
bash -c "$(curl -fsSL chalisehari.com.np/carchdev)"
.fi

.SH COMMANDS
.TP
\fBcheck-update\fR
Check for updates
.TP
\fBupdate\fR
Update the application
.TP
\fBuninstall\fR
Uninstall the application
.TP
\fBhelp\fR
Print this message or the help of the given subcommand(s)

.SH OPTIONS
.TP
\fB-l, --log\fR
Enable logging, output is on ~/.config/carch/carch.log
.TP
\fB-v, --version\fR
Print version information
.TP
\fB-c, --catppuccin-mocha\fR
Set theme to Catppuccin Mocha
.TP
\fB-d, --dracula\fR
Set theme to Dracula
.TP
\fB-g, --gruvbox\fR
Set theme to Gruvbox
.TP
\fB-n, --nord\fR
Set theme to Nord
.TP
\fB-r, --rose-pine\fR
Set theme to Rosé Pine
.TP
\fB-h, --help\fR
Print help

.SH SUPPORT
For assistance or to report issues, visit the official repository:
.br
https://github.com/harilvfs/carch

.SH DOCUMENTATION
Comprehensive documentation for Carch is available at:
.br
https://carch.chalisehari.com.np

.SH AUTHOR
Carch was developed and is maintained by Hari Chalise.
.br
Contact: \fIharilvfs@chalisehari.com.np\fR

.SH REPORTING BUGS
If you encounter bugs or issues, please report them at:
.br
https://github.com/harilvfs/carch/issues

.SH COPYRIGHT
Copyright (c) 2025 Hari Chalise.
.br
Released under the MIT License.
.br
Full license details: https://opensource.org/license/mit
