name-template: 'v$RESOLVED_VERSION 🌈'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '🚀 Features'
    labels:
      - 'feature'
      - 'enhancement'
      - 'arch'
      - 'fedora'
      - 'updates'
      - 'bash'
  - title: '🐛 Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
      - 'fixes'
      - 'refactor'
  - title: '🧰 Maintenance'
    labels:
      - 'chore'
  - title: '📝 Remove'
    labels:
      - 'remove'
  - title: '🔧 Custom'
    labels:
      - 'custom'
  - title: '🎨 UI/UX'
    labels:
      - 'UI/UX'
  - title: '📖 Docs'
    labels:
      - 'docs'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
change-title-escapes: '\<*_&' 
version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'
  default: patch
template: |
  ## Changes

  $CHANGES
