changelog:
  exclude:
    labels:
      - ignore-for-release
      - github-actions
    authors:
      - octocat
      - renovate[bot]

  categories:
    - title: '🚀 Features'
      labels:
        - 'enhancement'
    - title: '🦀 Rust'
      labels:
        - 'rust'
    - title: '🤖 CI'
      labels:
        - 'github-actions'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
    - title: '🔄 Refactoring'
      labels:
        - 'refactor'
    - title: '🎨 UI/UX'
      labels:
        - 'UI/UX'
    - title: '📖 Documentation'
      labels:
        - 'documentation'
    - title: '🔄 Other Changes'
      labels:
        - "*"

