version: "2"
linters:
  default: all
  enable:
    - gofmt
    - govet
    - errcheck
    - staticcheck
    - gosimple
    - unused
    - deadcode
    - structcheck
    - varcheck
    - ineffassign
    - gocyclo

run:
  timeout: 2m
