# https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "check"
env.CARGO_TERM_COLOR = "always"

[jobs]

[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.fmt]
command = ["cargo", "+nightly", "fmt"]

[jobs.nightly]
command = [
  "cargo",
  "check",
  "--all-targets",
  "--all-features",
  "--color",
  "always",
]
need_stdout = false

[jobs.test]
command = [
  "cargo",
  "test",
  "--color",
  "always",
  "--",
  "--color",
  "always",  # see https://github.com/Canop/bacon/issues/124
]
need_stdout = true
on_success = "play-sound(name=90s-game-ui-6,volume=50)"
on_failure = "play-sound(name=beep-warning,volume=100)"

[jobs.clippy]
command = ["cargo", "clippy", "--all-targets", "--color", "always"]
need_stdout = false

[jobs.run]
command = ["cargo", "run", "--color", "always"]
need_stdout = true
allow_warnings = true

[keybindings]
