 # https://github.com/Canop/bacon/blob/main/bacon.toml

default_job = "check"

env.CARGO_TERM_COLOR = "always"

[jobs.check]
command = ["cargo", "+nightly", "check", "--color", "always"]
need_stdout = false

[jobs.clippy]
command = [
    "cargo", "+nightly", "clippy",
    "--all-targets", "--all-features",
    "--color", "always"
]
need_stdout = false

[jobs.test]
command = [
    "cargo", "+nightly", "test",
    "--color", "always",
    "--", "--color", "always"
]
need_stdout = true

[jobs.run]
command = [
    "cargo", "+nightly", "run",
    "--color", "always",
    "--", "--dry-run"
]
need_stdout = true
allow_warnings = true

[jobs.fmt-check]
command = ["cargo", "+nightly", "fmt", "--", "--check"]
need_stdout = true

[jobs.fmt-fix]
command = ["cargo", "+nightly", "fmt"]
need_stdout = false

[keybindings]
alt-c = "job:clippy"
alt-t = "job:test"
alt-r = "job:run"
alt-f = "job:fmt-check"
alt-F = "job:fmt-fix"
