style = "conventional"
merge_commit = false
subject_capitalized = false
imperative_subject = true
subject_not_punctuated = true
line_length = 0
subject_length = 0
allowed_types = [
  "build",
  "chore",
  "ci",
  "docs",
  "feat",
  "fix",
  "perf",
  "refactor",
  "revert",
  "style",
  "test",
  "rust",
  "ui",
  "ux",
]
