# configuration for https://rust-lang.github.io/rustfmt/

# need rust nightly due to some fmt options are not on stable

use_small_heuristics = "Max"
reorder_modules = true
normalize_comments = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
match_arm_leading_pipes = "Preserve"
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
imports_granularity = "Module"
