# configuration for https://rust-lang.github.io/rustfmt/

# need rust nightly due to some fmt options are not on stable

max_width = 100
hard_tabs = false
tab_spaces = 4
use_small_heuristics = "Max"
newline_style = "Unix"
reorder_imports = true
reorder_modules = true
normalize_comments = true
struct_field_align_threshold = 20
enum_discrim_align_threshold = 20
match_arm_leading_pipes = "Preserve"
match_block_trailing_comma = true
blank_lines_upper_bound = 2
blank_lines_lower_bound = 0
trailing_comma = "Always"
format_code_in_doc_comments = true
wrap_comments = true
comment_width = 100
where_single_line = false
imports_granularity = "Module"
