# typos.toml - Configuration file for typos spellchecker

[default]
# Define custom word mappings to ignore specific cases
[default.extend-words]
ba = "ba"

# File-specific exclusions (uncomment if needed)
# [files]
# exclude = ["*.md", "CHANGELOG.md"]
