# typos.toml - Configuration file for typos spellchecker

[default]
[default.extend-words]
ratatui = "ratatui"
nstall = "nstall"
wil = "wil"
Nitch = "Nitch"

[files]
extend-exclude = ["CHANGELOG.md"]
