blank_issues_enabled: false 
contact_links:
  - name: Join our Discord server
    url: https://discord.com/invite/8NJWstnUHd
    about: Chat with the us.  
  - name: Read the Carch Documentation
    url: https://carch.chalisehari.com.np
    about: Find guides on installing, using, and configuring Carch scripts.

