[package]
name = "carch-installer"
version = "1.0.1"
edition = "2024"
description = "Platform-specific installer for Carch - A Simple Script to Make Linux System Setups Easier 🧩"
documentation = "https://carch-org.github.io/docs"
homepage = "https://github.com/harilvfs/carch"
readme = "../README.md"
repository = "https://github.com/harilvfs/carch/tree/main/platforms"
license-file = "../LICENSE"

categories = [
    "command-line-utilities"
]

keywords = [
    "system",
    "installer",
    "tui",
    "linux"
]

include = [
    "src/**",
    "Cargo.toml",
    "arch/**",
    "fedora/**"
]

[dependencies]
ratatui = "0.20"
crossterm = "0.25" 

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false 

[[bin]]
name = "carch-installer"
path = "src/main.rs" 
