# .cargo/config.toml

[build]
rustflags = ["-C", "target-cpu=native"]
target-dir = "build"

[profile.release]
opt-level = "z"
debug = false
lto = true
codegen-units = 1
panic = "abort"
strip = true
incremental = false

[term]
verbose = true
color = "always"

[env]
RUST_BACKTRACE = "1"
