[Alacritty]
description = "Alacritty is a fast, GPU-accelerated terminal emulator focused on performance and simplicity. The script applies my pre-configured Alacritty config to your system."

[Bash]
description = "The customizable command-line prompt for the Bash shell. The script lets you choose between Tokyo Night, Catppuccin, and Nord themes."

[Fish]
description = "Fish (Friendly Interactive Shell) is a user-friendly Unix shell with smart auto-suggestions, syntax highlighting, and easy scripting. The script installs and applies the tide theme."

[Foot]
description = "Foot is a lightweight, fast, minimal Wayland-native terminal emulator designed for simplicity and performance. The script applies my pre-configured Foot config."

[Ghostty]
description = "Ghostty is a fast, feature-rich, cross-platform terminal emulator using native UI and GPU acceleration. The script applies my pre-configured Ghostty config."

[Kitty]
description = "Kitty is a fast, GPU-accelerated terminal emulator with modern features like ligatures, tabs, tiling layouts, and image support. The script applies my pre-configured Kitty config."

[Tmux]
description = "tmux is a terminal multiplexer that lets you manage multiple terminal sessions within one window. The script applies my pre-configured tmux config."

[Zsh]
description = "Zsh (Z shell) is an advanced Unix shell with features like improved tab completion, better scripting, and powerful customization. The script installs all required dependencies and applies my custom theme."
