name = "Utilities"

[[data]]
name = "Auto Mount Drive"
description = "This utility is designed to help with automating the process of mounting a drive on to your system."
script = "auto-mount.sh"
task_list = "PFM"
multi_select = false

[[data]]
name = "Auto Login"
script = "auto-login.sh"
task_list = "DE setup"

[[data]]
name = "Numlock on Startup"
description = "This utility is designed to enable Num Lock at boot, rather than within desktop environments like KDE or GNOME"
script = "numlock.sh"
task_list = "PFM SS"
