name = "System Setup"

[[data]]
name = "Aur Helper"
description = "This script is designed to handle the installation and configuration of an AUR helper"
script = "aur.sh"
task_list = "I PFM"

[[data]]
name = "Wallpapers"
description = "This script is designed to handle the installation and configuration of wallpapers"
script = "wallpapers.sh"
task_list = "I PFM"

[[data]]
name = "Grub Theme"
description = "Installs ChrisTitusTech's Top 5 Bootloader Themes script to allow for easy customization of GRUB."
script = "grub.sh"
task_list = "PFM"

[[data]]
name = "Fonts"
description = "This script is designed to handle the installation and configuration of fonts"
script = "fonts.sh"
task_list = "I PFM"

[[data]]
name = "Sddm Theme"
description = "This script is designed to handle the installation and configuration of SDDM themes"
script = "sddm.sh"
task_list = "I PFM"

[[data]]
name = "Themes and Icons"
description = "This script is designed to handle the installation and configuration of themes and icons"
script = "themes-icons.sh"
task_list = "I PFM"

[[data]]
name = "Full System Cleanup"
description = "This script is designed to remove unnecessary packages, clean old cache files, remove temporary files, and to empty the trash."
script = "system-cleanup.sh"
task_list = "RP PFM"
multi_select = false

[[data]]
name = "Full System Update"
description = "This command updates your system to the latest packages available for your distro"
script = "system-update.sh"
task_list = "PFM"
multi_select = false

[[data]]
name = "Global Theme"
description = "This script is designed to handle the installation and configuration of global theming"
script = "global-theme.sh"
task_list = "I PFM"
