name = "Applications Setup"

[[data]]
name = "Communication Apps"
description = "Communication Apps is a collection of tools and scripts that help users with their daily communication tasks."
script = "communication.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Dev Tools"
description = "Developer Tools is a collection of tools and scripts that help developers with their daily tasks."
script = "dev.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Web Browsers"
description = "Web Browsers is a collection of tools and scripts that help users with their daily web browsing tasks."
script = "browsers.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Alacritty"
description = "Alacritty is a modern terminal emulator that comes with sensible defaults, but allows for extensive configuration. By integrating with other applications, rather than reimplementing their functionality, it manages to provide a flexible set of features with high performance. The supported platforms currently consist of BSD, Linux, macOS and Windows."
script = "alacritty.sh"
task_list = "I FM"

[[data]]
name = "DWM"
description= "Dwm is a dynamic window manager for X. It manages windows in tiled, monocle and floating layouts. All of the layouts can be applied dynamically, optimising the environment for the application in use and the task performed."
script = "dwm.sh"
task_list = "I PFM SS"

[[data]]
name = "Fastfetch"
description = "Fastfetch is a neofetch-like tool for fetching system information and displaying it prettily. It is written mainly in C, with performance and customizability in mind. "
script = "fastfetch.sh"
task_list = "I FM"

[[data]]
name = "Kitty"
description = "kitty is a free and open-source GPU-accelerated terminal emulator for Linux, macOS, and some BSD distributions, focused on performance and features. kitty is written in a mix of C and Python programming languages."
script = "kitty.sh"
task_list = "I FM"

[[data]]
name = "Rofi"
description = "Rofi is a window switcher, run dialog, ssh-launcher and dmenu replacement that started as a clone of simpleswitcher, written by Sean Pringle and later expanded by Dave Davenport."
script = "rofi.sh"
task_list = "I FM"

[[data]]
name = "i3wm"
description = "i3 is a tiling window manager designed for X11, inspired by wmii and written in C. It supports tiling, stacking, and tabbing layouts, which it handles dynamically. Configuration is achieved via plain text file and extending i3 is possible using its Unix domain socket and JSON-based IPC interface from many programming languages."
script = "i3wm.sh"
task_list = "I PFM SS"

[[data]]
name = "Hyprland"
description = "Hyprland is an independent, highly customizable, dynamic tiling Wayland compositor that doesn't sacrifice on its looks."
script = "hyprland.sh"
task_list = "I PFM SS"

[[data]]
name = "Sway WM"
description = "Sway is a tiling Wayland compositor and a drop-in replacement for the i3 window manager for X11. It works with your existing i3 configuration and supports most of i3's features, plus a few extras."
script = "swaywm.sh"
task_list = "I PFM SS"

[[data]]
name = "Neovim"
description = "Neovim is a refactor, and sometimes redactor, in the tradition of Vim (which itself derives from Stevie). It is not a rewrite but a continuation and extension of Vim. Many clones and derivatives exist, some very clever—but none are Vim. Neovim is built for users who want the good parts of Vim, and more."
script = "neovim.sh"
task_list = "I FM"

[[data]]
name = "Picom"
description = "Picom is a standalone compositor for Xorg, suitable for use with window managers that do not provide compositing. It is a fork of Compton, adding a more active development and better support for modern Xorg features."
script = "picom.sh"
task_list = "I PFM SS"

[[data]]
name = "Lts Kernel"
description = "The LTS Kernel is a long-term support kernel from the Linux kernel project. It is released every two years and receives bugfixes for two years. The LTS kernel is the best choice for users who do not want to update their kernel every few months."
script = "lts-kernel.sh"
task_list = "I PFM SS"

[[data]]
name = "Recording"
description = "This is the collection of screen recording tools that help users with their daily recording tasks."
script = "recording.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Editing"
description = "This is the collection of video editing tools that help users with their daily editing tasks."
script = "editing.sh"
task_list = "I"
multi_select = false

[[data]]
name = "File Managers"
description = "This is the collection of file managers that help users with their daily file management tasks."
script = "filemanager.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Multimedia"
description = "This is the collection of multimedia tools that help users with their daily multimedia tasks."
script = "multimedia.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Music"
description = "This is the collection of music tools that help users with their daily music tasks."
script = "music.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Terminal Emulators"
description = "This is the collection of terminal emulators that help users with their daily terminal tasks."
script = "terminal.sh"
task_list = "I"
multi_select = false

[[data]]
name = "Text Editors"
description = "This is the collection of text editors that help users with their daily text editing tasks."
script = "texteditor.sh"
task_list = "I"

[[data]]
name = "Thunar"
description = "Thunar is a modern file manager for the Xfce Desktop Environment. It has been designed from the ground up to be fast and easy-to-use. Its user interface is clean and intuitive, and does not include any confusing or useless options by default."
script = "thunar.sh"
task_list = "I"

[[data]]
name = "Android"
description = "This is the collection of Android tools that help users with their daily Android tasks."
script = "android.sh"
task_list = "I"
