name: Assign PR and Issues
on:
  pull_request:
    types: [opened]
  issues:
    types: [opened]
  workflow_dispatch:
permissions:
  pull-requests: write  
  contents: read
  issues: write
jobs:
  auto-assign:
    runs-on: ubuntu-latest
    steps:
      - name: Assign PR or Issue
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            if (context.payload.pull_request) {
              console.log('Assigning pull request...');
              await github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: context.payload.pull_request.number,
                assignees: ['harilvfs']
              });
            } else if (context.payload.issue) {
              console.log('Assigning issue...');
              await github.rest.issues.addAssignees({
                owner: context.repo.owner,
                repo: context.repo.repo,
                issue_number: context.payload.issue.number,
                assignees: ['harilvfs']
              });
            } else {
              console.log('Neither PR nor issue detected');
            }
