name: Label PRs
on:
  pull_request:
    types: [opened, synchronize, reopened]
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  label-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Get Commit Messages
        id: commits
        run: |
          messages=$(git log --format=%B -n 10)
          echo "messages<<EOF" >> "$GITHUB_ENV"
          echo "$messages" >> "$GITHUB_ENV"
          echo "EOF" >> "$GITHUB_ENV"
          echo "messages=$messages" >> "$GITHUB_OUTPUT"

      - name: Determine Labels
        id: labels
        run: |
          LABELS=()
          MESSAGES="${{ steps.commits.outputs.messages }}"
          
          [[ "$MESSAGES" =~ feat ]] && LABELS+=("enhancement")
          [[ "$MESSAGES" =~ fix ]] && LABELS+=("fixes")
          [[ "$MESSAGES" =~ docs ]] && LABELS+=("docs")
          [[ "$MESSAGES" =~ chore ]] && LABELS+=("dependencies")
          [[ "$MESSAGES" =~ refactor ]] && LABELS+=("refactor")
          [[ "$MESSAGES" =~ ci ]] && LABELS+=("github_actions")
          [[ "$MESSAGES" =~ remove ]] && LABELS+=("remove")
          [[ "$MESSAGES" =~ bug ]] && LABELS+=("bug")
          [[ "$MESSAGES" =~ rust ]] && LABELS+=("rust")
          [[ "$MESSAGES" =~ UX/UI ]] && LABELS+=("UX/UI")
          [[ "$MESSAGES" =~ bash ]] && LABELS+=("bash")
          [[ "$MESSAGES" =~ arch ]] && LABELS+=("arch")
          [[ "$MESSAGES" =~ fedora ]] && LABELS+=("fedora")
          [[ "$MESSAGES" =~ update ]] && LABELS+=("updates")
          [[ "$MESSAGES" =~ custom ]] && LABELS+=("custom")

          LABELS_JSON=$(printf '%s\n' "${LABELS[@]}" | jq -R . | jq -s .)
          echo "labels=$LABELS_JSON" >> "$GITHUB_ENV"

      - name: Apply Label
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const labels = JSON.parse(process.env.labels);
            github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              labels: labels
            });

