name: Generate Custom Badges

on:
  push:
    branches: [ main, master ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  generate-badges:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Install dependencies
        run: |
          npm init -y
          npm install d3 jsdom
          npm pkg set type=module
      
      - name: Generate badges
        id: badges
        run: |
          mkdir -p .github/badges
          
          cat > generate-badges.js << 'EOF'
          import fs from 'fs';
          import { execSync } from 'child_process';
          import { JSDOM } from 'jsdom';
          import * as d3 from 'd3';

          function runCommand(command) {
            try {
              return execSync(command).toString().trim();
            } catch (error) {
              return null;
            }
          }

          const ciStatus = process.env.GITHUB_ACTIONS ? "passing" : "unknown";

          const { window } = new JSDOM('<!DOCTYPE html><html><body></body></html>');
          const body = d3.select(window.document.body);

          const width = 150;
          const height = 40;

          const svg = body.append('svg')
            .attr('xmlns', 'http://www.w3.org/2000/svg')
            .attr('width', width)
            .attr('height', height)
            .attr('viewBox', `0 0 ${width} ${height}`);

          const defs = svg.append('defs');

          const bgGradient = defs.append('linearGradient')
            .attr('id', 'backgroundGradient')
            .attr('x1', '0%')
            .attr('y1', '0%')
            .attr('x2', '100%')
            .attr('y2', '0%');

          bgGradient.append('stop')
            .attr('offset', '0%')
            .attr('stop-color', '#24292e');

          bgGradient.append('stop')
            .attr('offset', '100%')
            .attr('stop-color', '#1a1e22');

          const passingGradient = defs.append('linearGradient')
            .attr('id', 'passingGradient')
            .attr('x1', '0%')
            .attr('y1', '0%')
            .attr('x2', '0%')
            .attr('y2', '100%');

          passingGradient.append('stop')
            .attr('offset', '0%')
            .attr('stop-color', '#2ecc71');

          passingGradient.append('stop')
            .attr('offset', '100%')
            .attr('stop-color', '#27ae60');

          const unknownGradient = defs.append('linearGradient')
            .attr('id', 'unknownGradient')
            .attr('x1', '0%')
            .attr('y1', '0%')
            .attr('x2', '0%')
            .attr('y2', '100%');

          unknownGradient.append('stop')
            .attr('offset', '0%')
            .attr('stop-color', '#f39c12');

          unknownGradient.append('stop')
            .attr('offset', '100%')
            .attr('stop-color', '#e67e22');

          const filter = defs.append('filter')
            .attr('id', 'dropShadow')
            .attr('x', '-20%')
            .attr('y', '-20%')
            .attr('width', '140%')
            .attr('height', '140%');

          filter.append('feGaussianBlur')
            .attr('in', 'SourceAlpha')
            .attr('stdDeviation', '1.5')
            .attr('result', 'blur');

          filter.append('feOffset')
            .attr('in', 'blur')
            .attr('dx', '0')
            .attr('dy', '1')
            .attr('result', 'offsetBlur');

          const feComponentTransfer = filter.append('feComponentTransfer')
            .attr('in', 'offsetBlur')
            .attr('result', 'lightenedBlur');

          feComponentTransfer.append('feFuncA')
            .attr('type', 'linear')
            .attr('slope', '0.2');

          const feMerge = filter.append('feMerge');
          feMerge.append('feMergeNode')
            .attr('in', 'lightenedBlur');
          feMerge.append('feMergeNode')
            .attr('in', 'SourceGraphic');

          svg.append('rect')
            .attr('x', 0)
            .attr('y', 0)
            .attr('width', width)
            .attr('height', height)
            .attr('rx', 6)
            .attr('ry', 6)
            .attr('fill', 'url(#backgroundGradient)')
            .attr('filter', 'url(#dropShadow)');

          svg.append('rect')
            .attr('x', 0)
            .attr('y', 0)
            .attr('width', 80)
            .attr('height', height)
            .attr('rx', 6)
            .attr('ry', 6)
            .attr('fill', '#555');

          svg.append('rect')
            .attr('x', 80)
            .attr('y', 0)
            .attr('width', width - 80)
            .attr('height', height)
            .attr('rx', 0)
            .attr('ry', 0)
            .attr('fill', ciStatus === "passing" ? 'url(#passingGradient)' : 'url(#unknownGradient)');

          svg.append('rect')
            .attr('x', width - 6)
            .attr('y', 0)
            .attr('width', 6)
            .attr('height', height)
            .attr('rx', 0)
            .attr('ry', 0)
            .attr('fill', ciStatus === "passing" ? 'url(#passingGradient)' : 'url(#unknownGradient)');

          svg.append('text')
            .attr('x', 40)
            .attr('y', height/2 + 5)
            .attr('text-anchor', 'middle')
            .attr('font-family', 'Arial, sans-serif')
            .attr('font-weight', 'bold')
            .attr('font-size', 16)
            .attr('fill', 'white')
            .text('CI');

          svg.append('text')
            .attr('x', 115)
            .attr('y', height/2 + 5)
            .attr('text-anchor', 'middle')
            .attr('font-family', 'Arial, sans-serif')
            .attr('font-weight', 'bold')
            .attr('font-size', 16)
            .attr('fill', 'white')
            .text(ciStatus);

          fs.writeFileSync('.github/badges/ci-status.svg', window.document.body.innerHTML);
          console.log("status badge generated successfully");
          EOF
          
          node generate-badges.js
          
          echo "Badge generated successfully"
      
      - name: Deploy badges to badges branch
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          
          git checkout -b badges || git checkout badges
          
          git add .github/badges/
          git commit -m "Update CI status badge" || echo "No changes to commit"
          
          git push -f origin badges
