name: CI
on:
  push:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - 'Cargo.lock'
  pull_request:
    branches: [main]
    paths:
      - '**/*.rs'
      - '**/*.toml'
      - 'Cargo.lock'
  workflow_dispatch:

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly
        with:
          components: rustfmt, clippy

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2
        with:
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock', '**/Cargo.toml') }}
          cache-directories: |
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            build/
          cache-on-failure: true

      - name: Install tools
        uses: taiki-e/install-action@v2
        with:
          tool: taplo-cli,cargo-deny

      - name: Run CI checks
        run: cargo xtask ci
