name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'scripts/**'

  pull_request:
    branches: [main]
    paths-ignore:
      - '**/*.md'
      - '.github/**'
      - 'scripts/**'

  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Add rustfmt component
        run: rustup component add rustfmt --toolchain nightly

      - name: Check formatting
        run: cargo +nightly fmt --all --check

  clippy:
    name: Lints
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install nightly Rust
        uses: dtolnay/rust-toolchain@nightly

      - name: Add clippy component
        run: rustup component add clippy --toolchain nightly

      - name: Check clippy
        run: cargo +nightly clippy

      - name: Check clippy with warnings denied
        run: cargo +nightly clippy -- -D warnings

      - name: Cargo check (default)
        run: cargo +nightly check --workspace --locked

      - name: Cargo check (no default features)
        run: cargo +nightly check --workspace --locked --no-default-features

      - name: Cargo check (all features)
        run: cargo +nightly check --workspace --locked --all-features

  taplo:
    name: Lint TOML files
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Taplo CLI
        run: cargo install taplo-cli --locked

      - name: Check TOML formatting
        run: taplo fmt --check

  deny:
    name: Check for crate advisories and bans
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install cargo-deny
        run: cargo install cargo-deny --locked

      - name: Run cargo deny check
        run: cargo deny check
