name: Lint Commits

on:
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

env:
  RUST_BACKTRACE: 1
  CARGO_TERM_COLOR: always
  CLICOLOR: 1

concurrency:
  group: "${{ github.workflow }}-${{ github.ref }}"
  cancel-in-progress: true

jobs:
  committed:
    name: Lint Commits
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # important to fetch full history so the range works

      - name: Lint Commits
        uses: crate-ci/committed@master
        with:
          args: origin/main..
