name: Update DATE.md

on:
  schedule:
    - cron: "0 0 * * *"  
  workflow_dispatch:  

permissions:
  contents: write
  pull-requests: write

jobs:
  update-date:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install Dependencies
        run: |
          pip install nepali-datetime requests

      - name: Generate DATE.md in Calendar Format with Quote
        run: |
          python - <<EOF
          from datetime import datetime
          import nepali_datetime
          import requests
          import random
          
          english_date = datetime.utcnow().strftime('%A, %d %B %Y')
          nepali_date = nepali_datetime.date.today().strftime('%A, %d %B %Y')
          
          # Fetch a random quote
          try:
              response = requests.get("https://api.quotable.io/random")
              quote_data = response.json()
              quote = f'"{quote_data["content"]}" - {quote_data["author"]}'
          except:
              fallback_quotes = [
                  "Believe you can and you're halfway there. - Theodore Roosevelt",
                  "The only way to do great work is to love what you do. - Steve Jobs",
                  "Do what you can, with what you have, where you are. - Theodore Roosevelt",
                  "It does not matter how slowly you go as long as you do not stop. - Confucius",
                  "Success is not final, failure is not fatal: it is the courage to continue that counts. - Winston Churchill"
              ]
              quote = random.choice(fallback_quotes)
          
          markdown_content = """<div align="center">
          
          # 📅 Date Calendar
          
          | English Date | Nepali Date |
          |-------------|-------------|
          | **{eng}** | **{nep}** |
          
          ## 🌟 Quote of the Day
          
          *{quote}*
          
          </div>
          """.format(eng=english_date, nep=nepali_date, quote=quote)
          
          with open("DATE.md", "w") as f:
              f.write(markdown_content)
          EOF

      - name: Commit and Push Changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add DATE.md
          git commit -m "Updated DATE.md with today's date and quote" || echo "No changes to commit"
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/${{ github.repository }}.git
