name: Go Lint & Format

on:
  push:
    branches: [main]
    paths:
      - '**/*.go'
  pull_request:
    branches: [main]
    paths:
      - '**/*.go'

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Check formatting (gofmt)
        run: |
          fmt_output=$(gofmt -l ./scripts/install)
          if [ -n "$fmt_output" ]; then
            echo "❌ The following files are not gofmt-ed:"
            echo "$fmt_output"
            echo ""
            echo "💡 Run 'gofmt -w ./scripts/install/' to fix formatting."
            exit 1
          fi

      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest

      - name: Run golangci-lint
        run: golangci-lint run --path-prefix scripts/install ./scripts/install/...
