name: Send Release Notifications

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version number without v prefix (e.g. 4.4.2)'
        required: true
      date:
        description: 'Release date (YYYY-MM-DD)'
        required: true

jobs:
  send-notifications:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get latest release
        id: latest_release
        uses: actions/github-script@v6
        with:
          script: |
            const { data: release } = await github.rest.repos.getLatestRelease({
              owner: context.repo.owner,
              repo: context.repo.repo
            });
            return release.tag_name;
          result-encoding: string

      - name: Prepare release message
        id: release_message
        run: |
          VERSION="v${{ github.event.inputs.version }}"
          DATE="${{ github.event.inputs.date }}"
          RELEASE_TAG="$VERSION"
          CHANGELOG_VERSION="${{ github.event.inputs.version }}"
          CHANGELOG_VERSION_NO_DOTS=$(echo "$CHANGELOG_VERSION" | tr -d '.')
          
          RELEASE_MESSAGE="✨ Carch version $VERSION is out! Check the release section for details. ✨\nhttps://github.com/harilvfs/carch/releases/tag/$RELEASE_TAG\nChangelog: https://github.com/harilvfs/carch/blob/main/CHANGELOG.md#$CHANGELOG_VERSION_NO_DOTS-$DATE"
          
          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Prepare Telegram message
        id: telegram_message
        run: |
          VERSION="v${{ github.event.inputs.version }}"
          DATE="${{ github.event.inputs.date }}"
          RELEASE_TAG="$VERSION"
          CHANGELOG_VERSION="${{ github.event.inputs.version }}"
          CHANGELOG_VERSION_NO_DOTS=$(echo "$CHANGELOG_VERSION" | tr -d '.')
          
          RELEASE_MESSAGE="✨ Carch version $VERSION is out! Check the release section for details. ✨\nhttps://github.com/harilvfs/carch/releases/tag/$RELEASE_TAG\nChangelog: https://github.com/harilvfs/carch/blob/main/CHANGELOG.md#$CHANGELOG_VERSION_NO_DOTS-$DATE"
          
          echo "text<<EOF" >> $GITHUB_OUTPUT
          echo "$RELEASE_MESSAGE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Send to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          RELEASE_MESSAGE: ${{ steps.release_message.outputs.text }}
        run: |
          FORMATTED_MESSAGE="${RELEASE_MESSAGE//$'\n'/\\n}"
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"$FORMATTED_MESSAGE\"}" \
            "$DISCORD_WEBHOOK_URL"

      - name: Send to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_THREAD_ID: ${{ secrets.TELEGRAM_THREAD_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d message_thread_id="$TELEGRAM_THREAD_ID" \
            -d text="${{ steps.telegram_message.outputs.text }}"
