name: Send Release Notes

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Extract version and date
        id: extract
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"  # e.g. v4.4.2
          VERSION="${TAG_NAME#v}"                          # strip 'v' → 4.4.2
          SHORT_VERSION="${VERSION//./}"                   # remove dots → 442
          DATE_RAW="${{ github.event.release.published_at }}"  # e.g. 2025-05-04T12:34:56Z
          DATE=$(echo "$DATE_RAW" | cut -d'T' -f1)         # extract YYYY-MM-DD
          CHANGELOG_ANCHOR="${SHORT_VERSION}-${DATE}"      # e.g. 442-2025-05-04

          echo "version=$VERSION" >> "$GITHUB_OUTPUT"
          echo "tag_name=$TAG_NAME" >> "$GITHUB_OUTPUT"
          echo "changelog_anchor=$CHANGELOG_ANCHOR" >> "$GITHUB_OUTPUT"

      - name: Send message to Discord
        env:
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          curl -H "Content-Type: application/json" \
            -X POST \
            -d "{\"content\": \"✨ Carch version ${{ steps.extract.outputs.tag_name }} is out! Check the release section for details. ✨\n\n${{ github.event.release.html_url }}\n\nChangelog: https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md#${{ steps.extract.outputs.changelog_anchor }}\"}" \
            "$DISCORD_WEBHOOK_URL"

      - name: Send message to Telegram
        env:
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_TOKEN/sendMessage" \
            -d chat_id="$TELEGRAM_CHAT_ID" \
            -d parse_mode="Markdown" \
            -d text="✨ *Carch version ${{ steps.extract.outputs.tag_name }} is out!* Check the release section for details. ✨%0A%0A[Release Tag](${{ github.event.release.html_url }})%0A[Changelog](https://github.com/${{ github.repository }}/blob/main/CHANGELOG.md#${{ steps.extract.outputs.changelog_anchor }})"

