name: Release Drafter
on:
  push:
    branches:
      - main
      - master
  pull_request:
    types: [opened, reopened, synchronize]
permissions:
  contents: read
jobs:
  update_release_draft:
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        with:
          # Include detailed commit information
          include-commits: true
          # Enable commit classification
          commit-analyzer: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
