name: Shell Format Check
on:
  push:
    branches: [ main ]
    paths:
      - '**/*.sh'
  pull_request:
    branches: [ main ]
    paths:
      - '**/*.sh'
  workflow_dispatch:

jobs:
  shell-format-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Setup Go
      uses: actions/setup-go@v6
      with:
        go-version: '1.23'

    - name: Install shfmt
      run: go install mvdan.cc/sh/v3/cmd/shfmt@latest

    - name: Check formatting
      run: |
        bash shfmt.sh
        git diff --exit-code
