name: Script Checks

on:
  push:
    paths:
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.sh'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Cache ShellCheck
        uses: actions/cache@v4
        with:
          path: ~/.cache/shellcheck
          key: ${{ runner.os }}-shellcheck

      - name: Run ShellCheck and Collect Issues
        id: shellcheck
        run: |
          mkdir -p reports
          shellcheck -x **/*.sh > reports/shellcheck.txt || true

      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@v3
        with:
          name: shellcheck-report
          path: reports/shellcheck.txt

  post-comment:
    name: Post Consolidated Comment
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ShellCheck Report
        uses: actions/download-artifact@v3
        with:
          name: shellcheck-report
          path: reports

      - name: Format and Post Comment
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -s reports/shellcheck.txt ]; then
            echo "## ShellCheck Report" > reports/comment.md
            echo '```' >> reports/comment.md
            cat reports/shellcheck.txt >> reports/comment.md
            echo '```' >> reports/comment.md

            gh pr comment ${{ github.event.pull_request.number }} --body-file reports/comment.md
          else
            echo "No ShellCheck issues found."
          fi
