name: Script Checks

on:
  push:
    paths:
      - '**/*.sh'
  pull_request:
    paths:
      - '**/*.sh'
  workflow_dispatch:

permissions:
  contents: read
  pull-requests: write

jobs:
  shellcheck:
    name: ShellCheck
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install ShellCheck
        run: sudo apt-get install -y shellcheck

      - name: Run ShellCheck and Collect Issues
        id: shellcheck
        run: |
          mkdir -p reports
          shellcheck -x **/*.sh > reports/shellcheck.txt || true

      - name: Upload ShellCheck Report
        uses: actions/upload-artifact@v4
        with:
          name: shellcheck-report
          path: reports/shellcheck.txt

  post-comment:
    name: Post Boxed Comments
    runs-on: ubuntu-latest
    needs: shellcheck
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Download ShellCheck Report
        uses: actions/download-artifact@v4
        with:
          name: shellcheck-report
          path: reports

      - name: Format and Post Boxed Comments
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ -s reports/shellcheck.txt ]; then
            echo "## ShellCheck Issues" > reports/comment.md

            while IFS= read -r line; do
              # Extract file, line number, and issue description
              file=$(echo "$line" | awk '{print $1}')
              line_number=$(echo "$line" | awk '{print $2}' | sed 's/://')
              issue=$(echo "$line" | cut -d' ' -f3-)

              # Create a boxed section for each issue
              echo "<details><summary><strong>${file} Line ${line_number}</strong></summary>" >> reports/comment.md
              echo '<pre>' >> reports/comment.md
              echo "$issue" >> reports/comment.md
              echo '</pre>' >> reports/comment.md
              echo "</details>" >> reports/comment.md
              echo "" >> reports/comment.md
            done < reports/shellcheck.txt

            gh pr comment ${{ github.event.pull_request.number }} --body-file reports/comment.md
          else
            echo "No ShellCheck issues found."
          fi
